version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: dependencies
    ignore:
      - dependency-name: "org.mockito:mockito-core"
        versions: [">= 5"]
      - dependency-name: "org.mockito:mockito-junit-jupiter"
        versions: [">= 5"]
      - dependency-name: "org.junit.jupiter:junit-jupiter-engine"
        versions: [">= 6"]
      - dependency-name: "org.junit.jupiter:junit-jupiter-params"
        versions: [">= 6"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    target-branch: master
